name: 'Terraform Preview'

on:
  push:
    branches:
    - main
    paths:
    - infrastructure/**
  pull_request:
    paths:
    - infrastructure/**

env:
  PM_USER: ${{ secrets.PM_USER}}
  PM_PASS: ${{ secrets.PM_PASS }}
  PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
  TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}


jobs:
  plan_staging:
    name: 'Plan'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform -chdir=infrastructure init
      - name: Terraform Format
        run: terraform -chdir=infrastructure fmt -check
      - name: Terraform Plan
        run: terraform -chdir=infrastructure plan
