name: 'Terraform'

on:
  push:
    branches:
    - main
    paths:
    - infrastructure/**
  pull_request:
    paths:
    - infrastructure/**
  workflow_dispatch:
    inputs:
      action:
        description: ''
        required: true
        default: 'plan'
        type: choice
        options:
        - apply
        - plan


env:
  PM_USER: ${{ secrets.PM_USER}}
  PM_PASS: ${{ secrets.PM_PASS }}
  PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
  TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}
  DNS_UPDATE_KEYNAME: "tsig-key."
  DNS_UPDATE_KEYSECRET: ${{ secrets.DNS_UPDATE_KEYSECRET }}
  DNS_UPDATE_KEYALGORITHM: hmac-sha256


jobs:
  plan:
    name: 'Plan'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform -chdir=infrastructure init
      - name: Terraform Format
        run: terraform -chdir=infrastructure fmt -check
      - name: Terraform Plan
        run: terraform -chdir=infrastructure plan
      - name: Terraform Apply
        if: ${{ inputs.action == 'apply'}}
        run: terraform -chdir=infrastructure apply -auto-approve
